# Generated by Django 2.2.9 on 2020-01-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0002_auto_20200127_1754'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpainting',
            unique_together={('user', 'painting')},
        ),
    ]
