# Generated by Django 2.2.8 on 2019-12-18 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPainting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_paintings', to='paintings.Painting', verbose_name='painting')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paintings', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user painting',
                'verbose_name_plural': 'user paintings',
                'db_table': 'user_paintings',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='UserPaintingLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painting_layer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_painting_layers', to='paintings.PaintingLayer', verbose_name='painting layer')),
                ('user_painting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='users.UserPainting', verbose_name='user painting')),
            ],
            options={
                'verbose_name': 'user painting layer',
                'verbose_name_plural': 'user painting layers',
                'db_table': 'user_painting_layers',
                'ordering': ('id',),
            },
        ),
    ]
