# Generated by Django 2.2.9 on 2020-02-17 14:23

import bobross.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_device_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-is_superuser', '-is_staff', 'id'), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.FileField(blank=True, null=True, upload_to=bobross.utils.file_directory, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='userpainting',
            name='progress',
            field=models.FileField(null=True, upload_to=bobross.utils.file_directory, verbose_name='progress'),
        ),
    ]
