# Generated by Django 2.2.8 on 2020-03-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200225_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpainting',
            name='complexity',
            field=models.TextField(blank=True, null=True, verbose_name='complexity'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.TextField(blank=True, null=True, verbose_name='state'),
        ),
        migrations.AlterUniqueTogether(
            name='userpainting',
            unique_together=set(),
        ),
    ]
