# Generated by Django 2.2.8 on 2019-12-18 12:16

import bobross.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('free', models.BooleanField(default=False, verbose_name='free')),
                ('position', models.PositiveIntegerField(blank=True, null=True, verbose_name='position')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('image', models.ImageField(null=True, upload_to=bobross.utils.upload_to, verbose_name='image')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paintings', to='categories.Category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'painting',
                'verbose_name_plural': 'paintings',
                'db_table': 'paintings',
                'ordering': ('position', 'title'),
            },
        ),
        migrations.CreateModel(
            name='PaintingLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, null=True, verbose_name='position')),
                ('image', models.ImageField(null=True, upload_to=bobross.utils.upload_to, verbose_name='image')),
                ('painting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='paintings.Painting', verbose_name='painting')),
            ],
            options={
                'verbose_name': 'painting layer',
                'verbose_name_plural': 'painting layers',
                'db_table': 'painting_layers',
                'ordering': ('position',),
            },
        ),
    ]
