# Generated by Django 2.2.9 on 2020-01-27 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paintings', to='paintings.Category', verbose_name='category'),
        ),
    ]
