# Generated by Django 2.2.9 on 2020-02-12 12:38

import bobross.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0002_auto_20200127_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='archive',
            field=models.FileField(null=True, upload_to=bobross.utils.file_directory, verbose_name='archive'),
        ),
    ]
