# Generated by Django 2.2.9 on 2020-02-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0003_painting_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='layers_count',
            field=models.PositiveIntegerField(null=True, verbose_name='layers count'),
        ),
        migrations.AddField(
            model_name='painting',
            name='size_name',
            field=models.CharField(max_length=55, null=True, verbose_name='size name'),
        ),
    ]
