# Generated by Django 2.2.9 on 2020-02-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0004_auto_20200225_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='painting',
            options={'verbose_name': 'painting', 'verbose_name_plural': 'paintings'},
        ),
    ]
